# Generated by Django 4.2.5 on 2023-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("email", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=5000)),
                ("story", models.TextField(max_length=50000)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "new"), ("resolved", "resolved")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
